### <font color='red'> Project 2 : Buzz Prediction on Twitter

Project Description:
- There are two different datasets for Regression and Classification tasks. Right-most column in both the datasets is a dependent variable i.e. buzz.
- Data description files are also provided for both the datasets.
- Deciding which dataset is for which task is part of the project.
- Read data into Jupyter notebook, use pandas to import data into a data frame.
- Preprocess data: Explore data, check for missing data and apply data scaling. Justify the type of scaling used.

Regression Task:
- Apply all the regression models you've learned so far. If your model has a scaling parameter(s) use Grid Search to find the best scaling parameter. Use plots and graphs to help you get a better glimpse of the results. 
- Then use cross-validation to find average training and testing score. 
- Your submission should have at least the following regression models: KNN regressor, linear regression, Ridge, Lasso, polynomial regression, SVM both simple and with kernels. 
- Finally, find the best regressor for this dataset and train your model on the entire dataset using the best parameters and predict buzz for the test_set.

Classification Task:
- Decide about a good evaluation strategy and justify your choice.
- Find best parameters for the following classification models: KNN classification, Logistic Regression, Linear Support Vector Machine, Kernelized Support Vector Machine, Decision Tree. 
- Which model gives the best results?

Deliverables:
- Submit IPython notebook. Use markdown to provide inline comments for this project.
- Rename notebook with your group number and submit only one notebook. Before submitting, make sure everything runs as expected. To check that, restart the kernel (in the menubar, select Kernel > Restart) and then run all cells (in the menubar, select Cell > Run All).
- Visualization encouraged.

Questions regarding the project:
- We have created a discussion board under Projects folder on e-learning. Create threads over there and post your queries related to project there.
- There is a high possibility that your classmate has also faced the same problem and knows the solution. So this is an effort to encourage collaborative learning, reducing mails for frequently asked queries and also making all the information available to everyone.
- Please check existing threads for your query before creating a new one. It goes without saying that do not share your code or complete solutions there.
- We will also answer queries there. We will not be answering any project related queries through the mail.

# Classification Models

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Data Preparation:

In [4]:
data = pd.read_table("Twitter-Absolute-Sigma-500.data",sep=",",header=None)

In [75]:
data.head()

0    1    2    3    4     5     6    7    8    9  ...    68   69   70  \
0  889  939  960  805  805  1143  1121  549  613  587 ...   1.0  1.0  889   
1  542  473  504  626  647   795   832  366  288  318 ...   1.0  1.0  542   
2   92   99  196  100  184    79   162   66   59  118 ...   1.0  1.0   92   
3   90   87   92  344  184   848   184   83   78   76 ...   1.0  1.0   90   
4  169   98  101   90   96    95   185  141   68   85 ...   1.0  1.0  169   

    71   72   73   74    75    76   77  
0  939  960  805  805  1143  1121  1.0  
1  473  504  626  647   795   832  1.0  
2   99  196  100  184    79   162  0.0  
3   87   92  344  184   848   184  1.0  
4   98  101   90   96    95   185  1.0  

[5 rows x 78 columns]

In [76]:
X_data = data.iloc[:,0:77]
Y_data = data.iloc[:,77]

In [77]:
X_data.head()

0    1    2    3    4     5     6    7    8    9   ...    67   68   69  \
0  889  939  960  805  805  1143  1121  549  613  587  ...   1.0  1.0  1.0   
1  542  473  504  626  647   795   832  366  288  318  ...   1.0  1.0  1.0   
2   92   99  196  100  184    79   162   66   59  118  ...   1.0  1.0  1.0   
3   90   87   92  344  184   848   184   83   78   76  ...   1.0  1.0  1.0   
4  169   98  101   90   96    95   185  141   68   85  ...   1.0  1.0  1.0   

    70   71   72   73   74    75    76  
0  889  939  960  805  805  1143  1121  
1  542  473  504  626  647   795   832  
2   92   99  196  100  184    79   162  
3   90   87   92  344  184   848   184  
4  169   98  101   90   96    95   185  

[5 rows x 77 columns]

In [78]:
Y_data.head()

0    1.0
1    1.0
2    0.0
3    1.0
4    1.0
Name: 77, dtype: float64

In [79]:
from sklearn.model_selection import train_test_split
X_whytouse, sampled_X, Y_whytouse, sampled_y = train_test_split(X_data, Y_data, shuffle = True, test_size = 0.01, random_state=42)
#Sampling the dataset so that it doesn't take a lot of time for processing

In [80]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
sampled_X = scaler.fit_transform(sampled_X)

We used MinMax scaler to scale the data. StandardScaler couldn't be used as the data has outliers, and so the spread is not uniform for all the data points. StandardScaler will not guarantee balanced feature scales. MinMaxScaler, will rescale the dataset such that all feature values are in the range 0 to 1.

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(sampled_X, sampled_y, shuffle = True, test_size = 0.30, random_state=42)

kNN Classifier:

In [82]:
from sklearn.grid_search import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import cross_val_score

In [83]:
k_range = list(range(1, 16))
print(k_range)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [84]:
param_grid = dict(n_neighbors=k_range)
print(param_grid)

{'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}


In [85]:
knn = KNeighborsClassifier(n_neighbors=k_range)

In [86]:
grid = GridSearchCV(knn, param_grid, cv=10, scoring='accuracy')

In [87]:
grid.fit(X_train, y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1,
           n_neighbors=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
           p=2, weights='uniform'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [88]:
print(grid.best_score_)
print(grid.best_params_)

0.9553299492385787
{'n_neighbors': 5}


In [89]:
knn_predict = grid.predict(X_test)

In [90]:
from sklearn.metrics import confusion_matrix
print("\nKNN confusion matrix:")
print(confusion_matrix(y_test, knn_predict))


KNN confusion matrix:
[[344   5]
 [ 16  58]]


In [91]:
from sklearn.metrics import classification_report
print("\nKNN scores:")
print(classification_report(y_test, knn_predict, target_names=["non buzz", "buzz"]))


KNN scores:
             precision    recall  f1-score   support

   non buzz       0.96      0.99      0.97       349
       buzz       0.92      0.78      0.85        74

avg / total       0.95      0.95      0.95       423



In [92]:
y_knn_predict = grid.predict(X_test)
y_knn_train_predict = grid.predict(X_train)

In [93]:
from sklearn.metrics import roc_auc_score
print('Train roc_auc_score: %.2f'%roc_auc_score(y_knn_train_predict, y_train))
print('Test roc_auc_score: %.2f '%roc_auc_score(y_knn_predict, y_test))

Train roc_auc_score: 0.95
Test roc_auc_score: 0.94 


In [94]:
report_table = [['knn', 'k = 5', grid.score(X_train, y_train), grid.score(X_test, y_test), roc_auc_score(y_knn_train_predict, y_train), roc_auc_score(y_knn_predict, y_test) ]]
report_table

[['knn',
  'k = 5',
  0.9614213197969543,
  0.950354609929078,
  0.9509050115962489,
  0.9380952380952381]]

Logistic Regression

In [95]:
from sklearn import linear_model

logistic = linear_model.LogisticRegression()
penalty = ['l1', 'l2']
C = [0.001, 0.01, 0.1, 1, 10, 100, 1000]
hyperparameters = dict(C=C, penalty=penalty)
grid_lg = GridSearchCV(logistic, hyperparameters, cv=5, scoring='accuracy')

In [96]:
grid_lg.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [97]:
print(grid_lg.best_score_)

0.9614213197969543


In [98]:
print(grid_lg.best_params_)

{'C': 1000, 'penalty': 'l2'}


In [99]:
lg_predict = grid_lg.predict(X_test)
lg_train_predict = grid_lg.predict(X_train)

In [100]:
from sklearn.metrics import confusion_matrix
print("\nLG confusion matrix:")
print(confusion_matrix(y_test, lg_predict))


LG confusion matrix:
[[345   4]
 [ 11  63]]


In [101]:
from sklearn.metrics import classification_report
print("\nLG scores:")
print(classification_report(y_test, lg_predict, target_names=["non buzz", "buzz"]))


LG scores:
             precision    recall  f1-score   support

   non buzz       0.97      0.99      0.98       349
       buzz       0.94      0.85      0.89        74

avg / total       0.96      0.96      0.96       423



In [102]:
from sklearn.metrics import roc_auc_score
print('Train roc_auc_score: %.2f'%roc_auc_score(lg_train_predict, y_train))
print('Test roc_auc_score: %.2f '%roc_auc_score(lg_predict, y_test))

Train roc_auc_score: 0.96
Test roc_auc_score: 0.95 


In [103]:
report_table =report_table + [['lg', 'C=1000, Penalty=12', grid_lg.score(X_train, y_train), grid_lg.score(X_test, y_test), roc_auc_score(lg_train_predict, y_train), roc_auc_score(lg_predict, y_test) ]]
report_table

[['knn',
  'k = 5',
  0.9614213197969543,
  0.950354609929078,
  0.9509050115962489,
  0.9380952380952381],
 ['lg',
  'C=1000, Penalty=12',
  0.9725888324873097,
  0.9645390070921985,
  0.9595904151134138,
  0.9546998155290961]]

Linear SVC

In [104]:
from sklearn.svm import LinearSVC

svc_lin = LinearSVC()
param_grid = {'C':[0.001, 0.01, 0.1, 1, 10, 100]}

grid_svc_lin = GridSearchCV(svc_lin, param_grid, cv = 10, scoring='accuracy')
grid_svc_lin.fit(X_train,y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [105]:
print(grid_svc_lin.best_score_)
print(grid_svc_lin.best_params_)

0.9573604060913705
{'C': 10}


In [106]:
lin_svc_predict = grid_svc_lin.predict(X_test)
lin_svc_train_predict = grid_svc_lin.predict(X_train)

In [107]:
from sklearn.metrics import confusion_matrix
print("\nLinSVC confusion matrix:")
print(confusion_matrix(y_test, lin_svc_predict))


LinSVC confusion matrix:
[[347   2]
 [ 12  62]]


In [108]:
from sklearn.metrics import classification_report
print("\nLinSVC scores:")
print(classification_report(y_test, lin_svc_predict, target_names=["non buzz", "buzz"]))


LinSVC scores:
             precision    recall  f1-score   support

   non buzz       0.97      0.99      0.98       349
       buzz       0.97      0.84      0.90        74

avg / total       0.97      0.97      0.97       423



In [109]:
from sklearn.metrics import roc_auc_score
print('Train roc_auc_score: %.2f'%roc_auc_score(lin_svc_train_predict, y_train))
print('Test roc_auc_score: %.2f '%roc_auc_score(lin_svc_predict, y_test))

Train roc_auc_score: 0.96
Test roc_auc_score: 0.97 


In [110]:
report_table =report_table + [['lin_svc', 'C=10', grid_svc_lin.score(X_train, y_train), grid_svc_lin.score(X_test, y_test), roc_auc_score(lin_svc_train_predict, y_train), roc_auc_score(lin_svc_predict, y_test) ]]
report_table

[['knn',
  'k = 5',
  0.9614213197969543,
  0.950354609929078,
  0.9509050115962489,
  0.9380952380952381],
 ['lg',
  'C=1000, Penalty=12',
  0.9725888324873097,
  0.9645390070921985,
  0.9595904151134138,
  0.9546998155290961],
 ['lin_svc',
  'C=10',
  0.9634517766497462,
  0.966903073286052,
  0.9550435279486403,
  0.9676619080779945]]

Kernalized SVC

In [111]:
from sklearn.svm import SVC
#Grid Search with Cross-Validation using cv=10
param_grid = {'C': [0.1, 1, 10, 100], 'gamma': [0.01, 0.1, 1, 10, 100]}
grid_svc = GridSearchCV(SVC(kernel='rbf'), param_grid, cv=10, scoring = 'accuracy', n_jobs=-1)
grid_svc.fit(X_train,y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=-1,
       param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [112]:
print("Best parameters: {}".format(grid_svc.best_params_))
print("Best cross-validation score: {:.4f}".format(grid_svc.best_score_))

Best parameters: {'C': 100, 'gamma': 1}
Best cross-validation score: 0.9635


In [113]:
svc_predict = grid_svc.predict(X_test)
svc_train_predict = grid_svc.predict(X_train)

In [114]:
from sklearn.metrics import confusion_matrix
print("\nSVC_predict confusion matrix:")
print(confusion_matrix(y_test, svc_predict))


SVC_predict confusion matrix:
[[343   6]
 [ 11  63]]


In [115]:
from sklearn.metrics import classification_report
print("\nSVC scores:")
print(classification_report(y_test, svc_predict, target_names=["non buzz", "buzz"]))


SVC scores:
             precision    recall  f1-score   support

   non buzz       0.97      0.98      0.98       349
       buzz       0.91      0.85      0.88        74

avg / total       0.96      0.96      0.96       423



In [116]:
from sklearn.metrics import roc_auc_score
print('Train roc_auc_score: %.2f'%roc_auc_score(svc_train_predict, y_train))
print('Test roc_auc_score: %.2f '%roc_auc_score(svc_predict, y_test))

Train roc_auc_score: 0.97
Test roc_auc_score: 0.94 


In [117]:
report_table =report_table + [['svc', 'C=100, gamma = 1', grid_svc.score(X_train, y_train), grid_svc.score(X_test, y_test), roc_auc_score(svc_train_predict, y_train), roc_auc_score(svc_predict, y_test) ]]
report_table

[['knn',
  'k = 5',
  0.9614213197969543,
  0.950354609929078,
  0.9509050115962489,
  0.9380952380952381],
 ['lg',
  'C=1000, Penalty=12',
  0.9725888324873097,
  0.9645390070921985,
  0.9595904151134138,
  0.9546998155290961],
 ['lin_svc',
  'C=10',
  0.9634517766497462,
  0.966903073286052,
  0.9550435279486403,
  0.9676619080779945],
 ['svc',
  'C=100, gamma = 1',
  0.9776649746192894,
  0.9598108747044918,
  0.968109759929613,
  0.940985015966593]]

Decsion Tree 

In [118]:
from sklearn.tree import DecisionTreeClassifier
param_grid = {'max_depth': [2, 4, 6, 8, 10, 12]}
grid_dt = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=10, scoring = 'accuracy')
grid_dt.fit(X_train,y_train)

GridSearchCV(cv=10, error_score='raise',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'max_depth': [2, 4, 6, 8, 10, 12]},
       pre_dispatch='2*n_jobs', refit=True, scoring='accuracy', verbose=0)

In [119]:
print("Best parameters: {}".format(grid_dt.best_params_))
print("Best cross-validation score: {:.4f}".format(grid_dt.best_score_))

Best parameters: {'max_depth': 2}
Best cross-validation score: 0.9655


In [120]:
dt_predict = grid_dt.predict(X_test)
dt_train_predict = grid_dt.predict(X_train)

In [121]:
from sklearn.metrics import confusion_matrix
print("\nDT_predict confusion matrix:")
print(confusion_matrix(y_test, dt_predict))


DT_predict confusion matrix:
[[342   7]
 [  9  65]]


In [122]:
from sklearn.metrics import classification_report
print("\nDT scores:")
print(classification_report(y_test, dt_predict, target_names=["non buzz", "buzz"]))


DT scores:
             precision    recall  f1-score   support

   non buzz       0.97      0.98      0.98       349
       buzz       0.90      0.88      0.89        74

avg / total       0.96      0.96      0.96       423



In [123]:
from sklearn.metrics import roc_auc_score
print('Train roc_auc_score: %.2f'%roc_auc_score(dt_train_predict, y_train))
print('Test roc_auc_score: %.2f '%roc_auc_score(dt_predict, y_test))

Train roc_auc_score: 0.96
Test roc_auc_score: 0.94 


In [124]:
report_table =report_table + [['DT', 'Max Depth = 2', grid_dt.score(X_train, y_train), grid_dt.score(X_test, y_test), roc_auc_score(dt_train_predict, y_train), roc_auc_score(dt_predict, y_test) ]]
report_table

[['knn',
  'k = 5',
  0.9614213197969543,
  0.950354609929078,
  0.9509050115962489,
  0.9380952380952381],
 ['lg',
  'C=1000, Penalty=12',
  0.9725888324873097,
  0.9645390070921985,
  0.9595904151134138,
  0.9546998155290961],
 ['lin_svc',
  'C=10',
  0.9634517766497462,
  0.966903073286052,
  0.9550435279486403,
  0.9676619080779945],
 ['svc',
  'C=100, gamma = 1',
  0.9776649746192894,
  0.9598108747044918,
  0.968109759929613,
  0.940985015966593],
 ['DT',
  'Max Depth = 2',
  0.9756345177664975,
  0.9621749408983451,
  0.9575395556367734,
  0.938568376068376]]

In [125]:
report = pd.DataFrame(report_table,columns = ['Model name', 'Model parameter', 'Train accuracy', 'Test accuracy', 'Train auc score', 'Test auc score'])

In [126]:
report.index = report['Model name']

In [127]:
report

Model name     Model parameter  Train accuracy  Test accuracy  \
Model name                                                                 
knn               knn               k = 5        0.961421       0.950355   
lg                 lg  C=1000, Penalty=12        0.972589       0.964539   
lin_svc       lin_svc                C=10        0.963452       0.966903   
svc               svc    C=100, gamma = 1        0.977665       0.959811   
DT                 DT       Max Depth = 2        0.975635       0.962175   

            Train auc score  Test auc score  
Model name                                   
knn                0.950905        0.938095  
lg                 0.959590        0.954700  
lin_svc            0.955044        0.967662  
svc                0.968110        0.940985  
DT                 0.957540        0.938568

Comparing the scores of the different models used above, we can determine the best model is Logistic Regression

In [128]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_data, Y_data, shuffle = True, test_size = 0.10, random_state=42)

In [129]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [130]:
log_reg = linear_model.LogisticRegression(penalty = 'l1', C = 1000)
log_reg.fit(X_train, y_train)

LogisticRegression(C=1000, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [131]:
train_score=log_reg.score(X_train,y_train)
test_score=log_reg.score(X_test,y_test)
print(train_score)
print(test_score)

0.9663602766985692
0.9575012436927013
